# scaredy cat
:toc:
:toclevels: 5

## Background
A cat clock with a camera inside. The cat's tail and eyes move as a pendulum with every "tick". When the camera detects a face, the tail and eyes stop moving until the face is no longer in the camera view.

https://photos.app.goo.gl/FYvWjFjmNzPmTfJi7[Photos & Videos]

## Installation
. `./install/install_dependencies.sh`
. `./install/install.sh`

## Administration
There are 2 services: scaredycat_tick_controller.service and scaredycat_main.service. Services can be restarted via:
....
sudo systemctl restart scaredycat_main.service scaredycat_tick_controller.service
....
Restarting one will automatically restart the other.

Logs can be viewed via:
....
journalctl | grep SCAREDYCAT
....

link:docs/viewing_live_camera_images_over_ssh.adoc[Preview the camera footage].

## Issues we've seen before
link:docs/issues_weve_seen_before.adoc[Issues we've seen before].

## Materials
. https://www.amazon.com/gp/product/B0019IBD3U/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1[Kit Cat Klock Gentlemen The Original (Classic Black)] (These come in two sizes - small and large. Make sure you get the large [original] one)
. 3D printed models: https://github.com/dasl-/scaredy-cat/tree/main/models
. Raspberry pi 4b
. https://www.pishop.us/product/raspberry-pi-camera-module-3/[Raspberry Pi Camera Module 3]
. Servo, electromagnet, and associated control circuitry

## Mounting
You will likely get better motion of the pendulum if you mount the clock on the wall very slightly off-center. Instead of aligning the clock straight up and down (12 o'clock), mount it towards 11 o'clock (head leaning to the left). This should be an almost imperceptible angle -- don't do anything drastic. Very subtle changes in alignment can have big impacts on the pendulum motion.
