# Viewing live camera images over SSH 
:toc:
:toclevels: 5

## Background
If you are using Raspbian Lite, which does not come with a GUI, you may struggle to determine what images the camera is capturing. Viewing a live feed of the camera is useful for debugging.

## Setup
Viewing the live feed of camera images over SSH requires installation of https://www.xquartz.org/[XQuartz] on macOS. 
....
brew install --cask xquartz
....

## Viewing live feed
1. Open XQuartz
1. In an XQuartz terminal: `ssh -XY <user>@<pi hostname or IP>`
1. Stop the service, if it's running, so that we don't have two copies of the program running: `sudo systemctl stop scaredycat_main.service`
1. Run the program with the preview flag: `sudo ./bin/tick_controller & ; ./bin/scaredycat  --show-preview`

## Known issues

### sudo
This method of viewing live camera images doesn't seem to work with `sudo`. It fails when running in XQuartz with https://gist.github.com/dasl-/35a7a9df94a35188e2307b6e6e2fa092[this error]. So don't run with `sudo`!

### "Could not load Qt platform plugin"
You may see an error like this:
....
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.9/dist-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
....

Follow the advice in this https://github.com/labelmeai/labelme/issues/842#issuecomment-826481652[github comment] - that is:
....
sudo mv /usr/local/lib/python3.9/dist-packages/cv2/qt/plugins /usr/local/lib/python3.9/dist-packages/cv2/qt/plugins.bak
....
